create table public.profiles (
  id bigint generated by default as identity primary key,
  username text not null,
  created_at timestamptz default now()
);

alter table public.profiles enable row level security;

create policy "Anyone can read profiles"
on public.profiles
for select
to anon, authenticated
using (true);